#!/bin/sh

touch /etc/crontabs/root
#语言自动
uci set luci.main.lang=auto
#设置默认主题
uci set luci.main.mediaurlbase=/luci-static/bootstrap
uci commit luci

uci set system.@system[0].timezone=UTC
uci set system.@system[0].zonename=UTC
############################################
# 参考: https://github.com/morrownr/USB-WiFi/discussions/145
# 解决接口报错不受支持的协议问题
# uci set network.lan
# uci set network.lan.ifname='eth0'
# uci set network.wan
# uci set network.wan.ifname='wan'
# uci set network.wan6
# uci set network.wan6.ifname='wan'
# uci set network.wan6.reqaddress='try'
# uci set network.wan6.reqprefix='auto'
uci commit system

uci set fstab.@global[0].anon_mount=1
uci commit fstab

ln -sf /sbin/ip /usr/bin/ip

sed -i "s#19.07-yuos#19.07.10#g" /etc/opkg/distfeeds.conf
sed -i '/lienol/d' /etc/opkg/distfeeds.conf
sed -i '/other/d' /etc/opkg/distfeeds.conf
#sed -i 's/downloads.openwrt.org/openwrt.proxy.ustclug.org/g' /etc/opkg/distfeeds.conf
#sed -i 's/http/https/g' /etc/opkg/distfeeds.conf
sed -i "s/# //g" /etc/opkg/distfeeds.conf
# 更改ipk源
sed -i 's#downloads.openwrt.org#mirrors.cloud.tencent.com/lede#g' /etc/opkg/distfeeds.conf

# 设置默认密码admin
#sed -i 's/root::0:0:99999:7:::/root:$1$wEehtjxj$YBu4quNfVUjzfv8p\/PBo5.:0:0:99999:7:::/g' /etc/shadow
#sed -i 's/root:::0:99999:7:::/root:$1$wEehtjxj$YBu4quNfVUjzfv8p\/PBo5.:0:0:99999:7:::/g' /etc/shadow

# 方案二：动态设置主机名
#
# 从 /tmp/sysinfo/model 获取设备型号（请根据实际情况修改路径）
# DEVICE_MODEL=$(cat /tmp/sysinfo/model 2>/dev/null)
# [ -z "$DEVICE_MODEL" ] && DEVICE_MODEL="OpenWrt"
# 若获取失败则使用默认值

# 设置系统主机名为设备型号
# uci set system.@system[0].hostname="${DEVICE_MODEL}"
# uci commit system

uci set dhcp.lan.ra='server'
uci -q del dhcp.lan.dhcpv6
uci set dhcp.lan.dns_service='0'
uci set dhcp.lan.ra_management='1'
uci -q del dhcp.lan.ra_slaac
uci set dhcp.lan.start='10'
uci set dhcp.lan.limit='150'
uci set dhcp.lan.leasetime='12h'
#uci set dhcp.@dnsmasq[0].localservice=0
#uci set dhcp.@dnsmasq[0].nonwildcard=0
uci commit dhcp

uci set network.wan.ifname='eth0.2'
uci set network.wan.proto='dhcp'

uci set network.lan.ipaddr='192.168.1.1'
uci set network.lan.netmask='255.255.255.0'
uci set network.lan.dns='8.8.8.8'
uci set network.lan.ip6assign='64'

uci commit network

# 禁用SSH开机启动
#uci set dropbear.@dropbear[0].enable='0'
#uci commit dropbear

sed -i '/option disabled/d' /etc/config/wireless
sed -i '/set wireless.radio${devidx}.disabled/d' /lib/wifi/mac80211.sh
wifi up

sed -i '/DISTRIB_DESCRIPTION/d' /etc/openwrt_release
echo "DISTRIB_DESCRIPTION='openwrt 19.07 yuos'" >> /etc/openwrt_release

# 删除状态页不需显示的
rm -rf /usr/lib/lua/luci/view/admin_status/index
#mv -f /usr/lib/lua/luci/view/admin_status/index /usr/lib/lua/luci/view/admin_status/index_backup 2>/dev/null

sed -i 's#openwrt/luci#lienol/openwrt-luci#g' /usr/lib/lua/luci/view/themes/*/footer.htm

#禁用某些可能会自启动且用不上的依赖包服务
/etc/init.d/php7-fastcgi disable 2>/dev/null
/etc/init.d/php7-fpm disable 2>/dev/null
/etc/init.d/php8-fastcgi disable 2>/dev/null
/etc/init.d/php8-fpm disable 2>/dev/null
/etc/init.d/softethervpnbridge disable 2>/dev/null
/etc/init.d/softethervpnserver disable 2>/dev/null
/etc/init.d/softethervpnclient disable 2>/dev/null
/etc/init.d/haproxy disable 2>/dev/null
/etc/init.d/kcptun disable 2>/dev/null

chmod 0755 /etc/init.d/*

rm -rf /tmp/luci-*cache

# 开启隐藏功能
echo "0xDEADBEEF" >> /etc/config/google_fu_mode

# 设置日志
sed -i '/log-facility/d' /etc/dnsmasq.conf
echo "log-facility=/dev/null" >> /etc/dnsmasq.conf
# 清空缓存
rm -rf /tmp/luci-modulecache/
rm -f /tmp/luci-indexcache

exit 0
