#!/bin/sh

touch /etc/crontabs/root

uci set luci.main.lang=zh_cn
#设置默认主题
#uci set luci.main.mediaurlbase=/luci-static/bootstrap_mod
uci commit luci

uci set system.@system[0].timezone=CST-8
uci set system.@system[0].zonename=Asia/Shanghai
uci commit system

uci set fstab.@global[0].anon_mount=1
uci commit fstab

ln -sf /sbin/ip /usr/bin/ip

sed -i '/lienol/d' /etc/opkg/distfeeds.conf
sed -i '/other/d' /etc/opkg/distfeeds.conf
#sed -i 's/downloads.openwrt.org/openwrt.proxy.ustclug.org/g' /etc/opkg/distfeeds.conf
#sed -i 's/http/https/g' /etc/opkg/distfeeds.conf
sed -i 's/# //g' /etc/opkg/distfeeds.conf

# 设置默认密码admin
sed -i 's/root::0:0:99999:7:::/root:$1$wEehtjxj$YBu4quNfVUjzfv8p\/PBo5.:0:0:99999:7:::/g' /etc/shadow
sed -i 's/root:::0:99999:7:::/root:$1$wEehtjxj$YBu4quNfVUjzfv8p\/PBo5.:0:0:99999:7:::/g' /etc/shadow
#uci set dhcp.lan.ra='server'
#uci set dhcp.lan.dhcpv6='server'
#uci set dhcp.lan.ra_management='1'
#uci set dhcp.lan.ra_default='1'
#uci set dhcp.@dnsmasq[0].localservice=0
#uci set dhcp.@dnsmasq[0].nonwildcard=0
uci delete dhcp.lan.ra
uci delete dhcp.lan.dhcpv6
uci delete dhcp.lan.ndp
uci commit dhcp

uci set network.lan.ipaddr='192.168.18.1'
uci set network.lan.netmask='255.255.255.0'
uci set network.lan.gateway='192.168.18.1'
uci set network.lan.dns='223.5.5.5 223.6.6.6 119.29.29.29 114.114.114.114 8.8.8.8'
uci set network.lan.ip6assign='64'
uci set network.lan.ifname='eth0'

# 参考: https://github.com/morrownr/USB-WiFi/discussions/145
# 解决接口报错不受支持的协议问题
uci set network.wan.device='eth0.2'
uci set network.wan.proto='dhcp'
uci set network.wan.ifname='eth0.2'
uci set network.wan6.device='eth0.2'
uci set network.wan6.proto='dhcpv6'
uci set network.wan6.ifname='eth0.2'
uci set network.wan6.reqaddress='try'
uci set network.wan6.reqprefix='auto'
uci set network.switch.name='switch0'
uci set network.switch.reset='1'
uci set network.switch.enable_vlan='1'
uci set network.switch_vlan.device='switch0'
uci set network.switch_vlan.vlan='1'
uci set network.switch_vlan.ports='1 4 6t'
uci set network.switch_vlan.device='switch0'
uci set network.switch_vlan.vlan='2'
uci set network.switch_vlan.ports='0 6t'
uci commit network

uci set firewall.zone.name='wan'
uci add_list firewall.network='wan'
uci add_list firewall.network='wan6'
uci set firewall.zone.input='REJECT'
uci set firewall.zone.output='ACCEPT'
uci set firewall.zone.forward='REJECT'
uci set firewall.zone.masq='1'
uci set firewall.zone.mtu_fix='1'
uci set firewall.forwarding.src='lan'
uci set firewall.forwarding.dest='wan'
uci commit firewall

uci set dhcp.wan=dhcp
uci set dhcp.wan.interface='wan'
uci set dhcp.wan.ignore='1'
uci commit dhcp

# 启用 UA2F
uci set ua2f.enabled.enabled=1
# 可选的防火墙配置选项
# 是否自动添加防火墙规则
uci set ua2f.firewall.handle_fw=1
# 是否尝试处理 443 端口的流量， 通常来说，流经 443 端口的流量是加密的，因此无需处理
uci set ua2f.firewall.handle_tls=1
# 是否处理微信的流量，微信的流量通常是加密的，因此无需处理。这一规则在启用 nftables 时无效
uci set ua2f.firewall.handle_mmtls=1
# 是否处理内网流量，如果你的路由器是在内网中，且你想要处理内网中的流量，那么请启用这一选项
uci set ua2f.firewall.handle_intranet=1
# 应用配置
uci commit ua2f
# 开机自启
service ua2f enable
# 启动 UA2F
service ua2f start


sed -i '/option disabled/d' /etc/config/wireless
sed -i '/set wireless.radio${devidx}.disabled/d' /lib/wifi/mac80211.sh
wifi up

# sed -i '/DISTRIB_DESCRIPTION/d' package/base-files/files/etc/banner
# echo "DISTRIB_DESCRIPTION='OpenWrt 21.02 @ 小渔学长 Build $(date +"%Y-%m-%d")'" >> /etc/openwrt_release
# echo -e '\n小渔学长 Build @ '$(date +%Y-%m-%d)'\n'  >> package/base-files/files/etc/banner

# sed -i '/DISTRIB_REVISION/d' package/base-files/files/etc/openwrt_release
# echo "DISTRIB_REVISION='$(TZ=CST-8 date "+%Y.%m.%d")'" >> package/base-files/files/etc/openwrt_release

# sed -i '/DISTRIB_DESCRIPTION/d' package/base-files/files/etc/openwrt_release
# echo "DISTRIB_REVISION='$(TZ=CST-8 date "+%Y.%m.%d")'" >> package/base-files/files/etc/openwrt_release

sed -i '/DISTRIB_DESCRIPTION/d' /etc/openwrt_release
echo "DISTRIB_DESCRIPTION='Yuos @ 小渔学长 Build $(date +"%Y-%m-%d")'" >> /etc/openwrt_release
# 

# 删除状态页不需显示的
rm -rf /usr/lib/lua/luci/view/admin_status/index
#mv -f /usr/lib/lua/luci/view/admin_status/index /usr/lib/lua/luci/view/admin_status/index_backup 2>/dev/null

sed -i 's#openwrt/luci#lienol/openwrt-luci#g' /usr/lib/lua/luci/view/themes/*/footer.htm

#禁用某些可能会自启动且用不上的依赖包服务
/etc/init.d/php7-fastcgi disable 2>/dev/null
/etc/init.d/php7-fpm disable 2>/dev/null
/etc/init.d/php8-fastcgi disable 2>/dev/null
/etc/init.d/php8-fpm disable 2>/dev/null
/etc/init.d/softethervpnbridge disable 2>/dev/null
/etc/init.d/softethervpnserver disable 2>/dev/null
/etc/init.d/softethervpnclient disable 2>/dev/null
/etc/init.d/haproxy disable 2>/dev/null
/etc/init.d/kcptun disable 2>/dev/null

chmod 0755 /etc/init.d/*

rm -rf /tmp/luci-*cache

# 开启隐藏功能
echo "0xDEADBEEF" >> /etc/config/google_fu_mode

exit 0
